//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralsUltimateExperience.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Original")]
        public string CurrentHeureHMod {
            get {
                return ((string)(this["CurrentHeureHMod"]));
            }
            set {
                this["CurrentHeureHMod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChangingHeureHMod {
            get {
                return ((bool)(this["ChangingHeureHMod"]));
            }
            set {
                this["ChangingHeureHMod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Original")]
        public string CurrentGeneralsMod {
            get {
                return ((string)(this["CurrentGeneralsMod"]));
            }
            set {
                this["CurrentGeneralsMod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChangingGeneralsMod {
            get {
                return ((bool)(this["ChangingGeneralsMod"]));
            }
            set {
                this["ChangingGeneralsMod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentGeneralsMapPack {
            get {
                return ((int)(this["CurrentGeneralsMapPack"]));
            }
            set {
                this["CurrentGeneralsMapPack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentHeureHMapPack {
            get {
                return ((int)(this["CurrentHeureHMapPack"]));
            }
            set {
                this["CurrentHeureHMapPack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ZoomMaxCameraHeight {
            get {
                return ((int)(this["ZoomMaxCameraHeight"]));
            }
            set {
                this["ZoomMaxCameraHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double ZoomCameraAdjustSpeed {
            get {
                return ((double)(this["ZoomCameraAdjustSpeed"]));
            }
            set {
                this["ZoomCameraAdjustSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ZoomDrawEntireTerrain {
            get {
                return ((bool)(this["ZoomDrawEntireTerrain"]));
            }
            set {
                this["ZoomDrawEntireTerrain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JustUpdated {
            get {
                return ((bool)(this["JustUpdated"]));
            }
            set {
                this["JustUpdated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScrollGregware {
            get {
                return ((bool)(this["ScrollGregware"]));
            }
            set {
                this["ScrollGregware"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FullscreenMode {
            get {
                return ((int)(this["FullscreenMode"]));
            }
            set {
                this["FullscreenMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CurrentForceZoom {
            get {
                return ((bool)(this["CurrentForceZoom"]));
            }
            set {
                this["CurrentForceZoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Current4g {
            get {
                return ((bool)(this["Current4g"]));
            }
            set {
                this["Current4g"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CurrentLaunchActivatedGenerals {
            get {
                return ((bool)(this["CurrentLaunchActivatedGenerals"]));
            }
            set {
                this["CurrentLaunchActivatedGenerals"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CurrentLaunchActivatedHeureH {
            get {
                return ((bool)(this["CurrentLaunchActivatedHeureH"]));
            }
            set {
                this["CurrentLaunchActivatedHeureH"] = value;
            }
        }
    }
}
