//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneralsUltimateExperience.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Original")]
        public string CurrentHeureHMod {
            get {
                return ((string)(this["CurrentHeureHMod"]));
            }
            set {
                this["CurrentHeureHMod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChangingHeureHMod {
            get {
                return ((bool)(this["ChangingHeureHMod"]));
            }
            set {
                this["ChangingHeureHMod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Original")]
        public string CurrentGeneralsMod {
            get {
                return ((string)(this["CurrentGeneralsMod"]));
            }
            set {
                this["CurrentGeneralsMod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChangingGeneralsMod {
            get {
                return ((bool)(this["ChangingGeneralsMod"]));
            }
            set {
                this["ChangingGeneralsMod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentGeneralsMapPack {
            get {
                return ((int)(this["CurrentGeneralsMapPack"]));
            }
            set {
                this["CurrentGeneralsMapPack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentHeureHMapPack {
            get {
                return ((int)(this["CurrentHeureHMapPack"]));
            }
            set {
                this["CurrentHeureHMapPack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CurrentGeneralsGentool {
            get {
                return ((bool)(this["CurrentGeneralsGentool"]));
            }
            set {
                this["CurrentGeneralsGentool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CurrentHeureHGentool {
            get {
                return ((bool)(this["CurrentHeureHGentool"]));
            }
            set {
                this["CurrentHeureHGentool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CurrentGeneralsForceZoom {
            get {
                return ((bool)(this["CurrentGeneralsForceZoom"]));
            }
            set {
                this["CurrentGeneralsForceZoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CurrentHeureHForceZoom {
            get {
                return ((bool)(this["CurrentHeureHForceZoom"]));
            }
            set {
                this["CurrentHeureHForceZoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FullscreenModeGregware {
            get {
                return ((bool)(this["FullscreenModeGregware"]));
            }
            set {
                this["FullscreenModeGregware"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int ZoomMaxCameraHeight {
            get {
                return ((int)(this["ZoomMaxCameraHeight"]));
            }
            set {
                this["ZoomMaxCameraHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double ZoomCameraAdjustSpeed {
            get {
                return ((double)(this["ZoomCameraAdjustSpeed"]));
            }
            set {
                this["ZoomCameraAdjustSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ZoomDrawEntireTerrain {
            get {
                return ((bool)(this["ZoomDrawEntireTerrain"]));
            }
            set {
                this["ZoomDrawEntireTerrain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JustUpdated {
            get {
                return ((bool)(this["JustUpdated"]));
            }
            set {
                this["JustUpdated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScrollGregware {
            get {
                return ((bool)(this["ScrollGregware"]));
            }
            set {
                this["ScrollGregware"] = value;
            }
        }
    }
}
